version: 2

run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - gocritic
    - revive

  settings:
    revive:
      severity: warning
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: package-comments
        - name: exported
          disabled: true


issues:
  exclude-use-default: false
